# .github/workflows/linter-reusable-workflow.yml
name: Reusable Linter Workflow

on:
  workflow_call:
    inputs:
      lint-config:
        required: false
        type: string
        default: ".github/.superlinter.yml"

jobs:
  lint-code:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Run Super Linter
        uses: github/super-linter@v4
        with:
          config_file: ${{ inputs.lint-config }}
