# .github/workflows/main-ci.yml
name: Main CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  zap-scan:
    uses: MikeDiWilson/ci-automation/.github/workflows/zap-reusable-workflow.yml@main
    with:
      environment: "test"
    secrets:
      ZAP_API_KEY: ${{ secrets.ZAP_API_KEY }}

  linting:
    uses: your-repo-name/your-repo/.github/workflows/ktlint-reusable.yml@main
    with:
      java-version: '17'  # Specify the required Java version     
