# .github/workflows/zap-reusable-workflow.yml
name: Reusable ZAP Scan Workflow

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        default: "test"
    secrets:
      ZAP_API_KEY:
        required: true

jobs:
  zap-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Run ZAP Scan
        run: |
          echo "Running ZAP scan on environment: ${{ inputs.environment }}"
          docker run -v $(pwd):/zap/wrk/:rw -t ghcr.io/zaproxy/zaproxy:stable zap-baseline.py -t http://localhost
        env:
          ZAP_API_KEY: ${{ secrets.ZAP_API_KEY }}
